# Configurations postgresql
# Database
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-217-236-206.eu-west-1.compute.amazonaws.com:5432/daadjg5q41p10e
    username: uprsvkhztuuodr
    password: 313d534298f3cb4afeaf458e1a14e9154eeac6823040edacff51c972c76455ea
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
# Server configuration
server:
  port: 9090
