# Configurations postgresql
# Database
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-52-31-94-195.eu-west-1.compute.amazonaws.com:5432/d2ptaklsnhlitn
    username: tlhmprnzgwfyxu
    password: ea2ec022530657f865bcba1260745e6e9a91c6f45648896462d5208a6cc6533c
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
# Server configuration
server:
  port: 9090
